

Welcome to the webpage of the practical sessions of the course [Machine learning and stochastic control](https://finance.math.upmc.fr/enseignements/2_mn_9_ml_stochastic_control/) taught by Professor [Pham](https://sites.google.com/site/phamxuanhuyen/) within the Master’s program in Probability and Finance (M2).


## Global informations  {.unnumbered}

:::{#method-description .methodology}



<span class="para-title">Prerequisites :</span>

- Good knowledge on **Probability Theory** and **Stochastic Processes**.
- Basics on **optimal control theory**.
- Basics on **Deep Learning**.
- Familarity with **Python** and potentially with **PyTorch**.

<span class="para-title">Schedule :</span>

- **Lab work** n°  $1$  : Tuesday, January 27th,  9h-12h, room $102$ in tower $15-25$.
- **Lab work** n°  $2$  : Tuesday, February 3rd,  9h-12h, room $102$ in tower $15-25$.
- **Lab work** n°  $3$  : Tuesday, February 19th, 9h-12h,
room $102$ in tower $15-25$.

<span class="para-title">Materials :</span>

The practical sessions will be conducted in **Python**. You should bring your own laptop and have your own **Python** environment set up for each session.
 
 <span class="para-title">Planning :</span>
 

 - <span class="para-subtitle"> Lab work n°1 : Deep PDE Solver </span>

 The first lab session will be about **Deep PDE Solver** for solving partial differential equations using neural networks. You will implement some of the algorithms which were seen during the course. 

  - <span class="para-subtitle"> Lab work n°2 : RL for stochastic control problems </span>


The second lab session will be about **Reinforcement Learning** for solving some control problems. We will implement some of the algorithms seen during the course 
About **Reinforcement Learning** for stochastic control problems.

  - <span class="para-subtitle"> Lab work n°3 : GenAI for data generation </span>


The third lab session will be about **Generative IA** for data generation based on the **Schrödinger bridge**. You will implement the **Schrödinger Bridge Time series (SBTS)** algorithm and apply it to generate some **new samples** of generic time series. 


 <span class="para-title">Grade :</span>

You will have to choose **one lab (TP)** among the three proposed by modifying the column named **"Lab Choice"** associated to your name directly on the  **Excel sheet** available [here](https://docs.google.com/spreadsheets/d/1H2ZDF7BeY9pMEMaEnG-JyBBCpDcvnkJcoZzA4M7mCMo/edit?gid=0#gid=0). Note that the project has be to done by **groups** of **2** or **3**.
\
Your objective will be to answer the **questions** of the chosen lab, and a fairly open-ended **mini-project** will be proposed at the end of it. 

**The final grade** will be based on both the **lab questions** and the **mini-project**. In any case, the **final course grade** will be calculated as follows:

<div class="eq-frame">

\begin{align}
    \text{Final Grade = 50 \% multiple-choice exam (QCM) + 50 \% project}.
\end{align}

</div>


 <span class="para-title">Questions ? :</span>

If you have any  **questions**, you can either e-mail [Samy](mailto:samy.mekkaoui@polytechnique.edu) or [Alexandre](mailto:alexandre.alouadi@polytechnique.edu) who prepared the lab sessions for this course.

:::



## Use this website {.unnumbered}


:::{#method-description .methodology}

<span class="para-title">Structure of the website :</span>

The site is structured into three sections that make up the course, each consisting of two chapters.

  - <span class="para-subtitle"> Course reminders: </span>

The first chapter, titled **Course Reminders**, reviews the key theoretical concepts covered in the course. It revisits important results and the corresponding algorithms for the underlying problems.


  - <span class="para-subtitle"> Practical session: </span>
  
The second chapter, titled **Lab Work**, contains the practical session instructions along with a link to a **Jupyter Notebook** where you can write your code. These notebooks are designed to be self-contained, allowing you to work independently during the sessions.

At the end of each practical session, an **open-ended project** is provided. This project is not intended to be completed during the session, but it is closely related to the material covered and offers an opportunity to explore the concepts in more depth.


  - <span class="para-subtitle"> References: </span>

The site includes a **References** section, where we list the key papers forming the core content of this course. Much of this material is relatively recent and represents an active area of research. Feel free to contact us if you are interested in exploring these topics further!

  - <span class="para-subtitle"> Appendix: </span>

The site also includes an **Appendix** section, where we explore in greater depth some of the topics covered in the course. This section is still under development and will be updated regularly throughout the year.







For your information, this site is generated using [Quarto](https://quarto.org) through GitHub Pages (see this [GitHub](https://github.com/SamyMekk/TP-Controle-Stochastique) page). If you spot any errors on the site, feel free to report them through pull requests.

:::

## Acknowledgements {.unnumbered}

:::{#method-description .methodology}

We would like to thank the following individuals and organizations without whose support this course would not be possible

- Professor [Huyên Pham](https://sites.google.com/site/phamxuanhuyen/) for the support and valuable feedbacks during the creation of this lab.
- **Participants** in the course for your interest in Machine Learning for stochastic control and its applications.
:::

